"""Writes game/data/phantoms/gear.txt: the equipment phantom players (bots) may wear.

Only Interlude or Kamael items (aCis ids + kamael.item_ids), so bots never show
later-chronicle gear. Armor comes as whole sets from data/stats/armorsets.

Line formats:
  weapon <grade> <weapon type> <magic 0|1> <item id>   # name
  set <grade> <LIGHT|HEAVY|MAGIC> <chest> <legs> <head> <gloves> <feet> <shield>   # name (0 = no such part)

Usage: python tools/interlude/build_phantom_gear.py
"""

import xml.etree.ElementTree as ET

import checks
import datasets as ds

OUT = ds.GAME / "data" / "phantoms" / "gear.txt"
GRADES = ["NONE", "D", "C", "B", "A", "S"]
WEAPON_TYPES = {"SWORD", "BLUNT", "DAGGER", "BOW", "POLE", "DUAL", "FIST", "DUALFIST", "RAPIER", "ANCIENTSWORD", "CROSSBOW", "DUALDAGGER"}


def templates():
	"""id -> (element, sets dict) for weapons and armors."""
	result = {}
	for f in ds._xml_files(ds.GAME / "data" / "stats" / "items"):
		for it in ET.parse(f).getroot().findall("item"):
			if it.get("type") in ("Weapon", "Armor"):
				result[int(it.get("id"))] = (it, ds._sets(it))
	return result


def main():
	allowed = checks.allowed_items()
	items = templates()
	lines = ["# Generated by tools/interlude/build_phantom_gear.py, do not edit by hand."]

	weapons = 0
	for item_id, (it, sets) in sorted(items.items()):
		grade = (sets.get("crystal_type") or "NONE").upper()
		kind = (sets.get("weapon_type") or "").upper()
		if it.get("type") != "Weapon" or item_id not in allowed or grade not in GRADES or kind not in WEAPON_TYPES:
			continue
		if sets.get("is_questitem") == "true" or int(sets.get("price") or 0) == 0:
			continue
		magic = 1 if sets.get("is_magic_weapon") == "true" else 0
		lines.append(f"weapon {grade} {kind} {magic} {item_id}  # {it.get('name')}")
		weapons += 1

	armor_sets = 0
	for f in ds._xml_files(ds.GAME / "data" / "stats" / "armorsets"):
		for s in ET.parse(f).getroot().findall("set"):
			chest = int(s.find("chest").get("id"))
			if chest not in allowed or chest not in items:
				continue
			sets = items[chest][1]
			grade = (sets.get("crystal_type") or "NONE").upper()
			armor = (sets.get("armor_type") or "").upper()
			if grade not in GRADES or armor not in ("LIGHT", "HEAVY", "MAGIC"):
				continue

			def part(tag):
				return next((int(p.get("id")) for p in s.findall(tag) if int(p.get("id")) in allowed and int(p.get("id")) in items), 0)

			parts = [part(tag) for tag in ("legs", "head", "gloves", "feet", "shield")]
			lines.append(f"set {grade} {armor} {chest} {' '.join(map(str, parts))}  # {items[chest][0].get('name')}")
			armor_sets += 1

	OUT.parent.mkdir(exist_ok=True)
	OUT.write_text("\n".join(lines) + "\n", encoding="utf-8", newline="\n")
	print(f"{OUT.relative_to(ds.ROOT)}: {weapons} weapons, {armor_sets} armor sets")


if __name__ == "__main__":
	main()
