# ---------------------------------------------------------------------------
# Database
# ---------------------------------------------------------------------------

# Database URL
# Default: jdbc:mariadb://localhost/l2jls
URL = jdbc:mysql://localhost:3307/l2jdb_custom

# Database User
# Default: l2j
User = root

# Database Password
# Default: l2jserver2019
Password = root

# Default: 10
MaxConnections = 10

# Default: 0
MaxIdleTime = 0